Draft of Signup and Login Usecase
CSC207-2022F-UofT/course-project-fitbook pull request #23
Opened 2022-11-21 15:53 UTC by modaserMoj

2022-11-21 16:20 UTC, youssefsoli requested changes
The structure and logic look good, there are just a few small style issues and nit picks.

2022-11-21 16:20 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/adapter/web/UserLoginController.java
> +    String createPost(Model model, @RequestBody UserLoginCommand command) {
This should map to /login and the method should be called userLogin() or something.

2022-11-21 16:20 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/adapter/web/UserRegisterController.java
> +    String createPost(Model model, @RequestBody UserRegisterCommand command) {
ditto

2022-11-21 16:20 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/application/port/out/response/UserLoginResponse.java
> +
Extra space

2022-11-21 16:20 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/application/service/UserLoginService.java
> +
Extra spaces

2022-11-21 16:20 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/application/service/UserLoginService.java
> +    @ResponseStatus(value= HttpStatus.INTERNAL_SERVER_ERROR, reason="Incorrect Password")
Find a better status code maybe, a 401 Unauthorized for wrong password

2022-11-21 16:20 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/application/service/UserLoginService.java
> +    @ResponseStatus(value= HttpStatus.INTERNAL_SERVER_ERROR, reason="User Not Found")
User not found should probably be a 422 Unprocessable Entity

2022-11-21 16:37 UTC, modaserMoj commented
The reviewer requested changes were made

2022-11-22 03:08 UTC, jpablo2002 approved these changes
Code is written cleanly and the creation of custom exceptions is great to better represent the cause of the errors! Looks good to me!

2022-11-22 03:17 UTC, youssefsoli requested changes

2022-11-22 03:17 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/application/port/out/response/UserRegisterResponse.java
> +    String id;
ditto

2022-11-22 03:17 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/application/service/UserRegisterService.java
> +            super("Name is too long by "+ ((command.getName().length())-40)+" characters");
Add space between operators

2022-11-22 03:17 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/application/service/UserRegisterService.java
> +            super("Password is too long by "+ ((command.getName().length())-40)+" characters");
ditto

2022-11-22 03:20 UTC, jannater commented
Good job with clean architecture and  hexagonal architecture while implementing the use cases.

2022-11-22 03:51 UTC, youssefsoli commented on src/main/java/ca/utoronto/fitbook/application/service/UserRegisterService.java
> +        }
```suggestion
        if (!command.getPassword().equals(command.getRepeatedPassword()))
            throw new PasswordNotMatch();
         if (command.getName().length() > 40)
            throw new NameTooLong(command);
        if (command.getPassword().length() < 8)
            throw new PasswordTooShort();
        if (command.getPassword().length() > 40)
            throw new PasswordTooLong(command);
```

2022-11-22 04:03 UTC, Ludosss approved these changes
looks good!

2022-11-22 04:08 UTC, jpablo2002 approved these changes
Looks good! Great fixes!

2022-11-22 04:08 UTC, merged