Implement exercise list port
CSC207-2022F-UofT/course-project-fitbook pull request #30
Opened 2022-11-21 16:47 UTC by jpablo2002

2022-11-21 16:55 UTC, Ludosss requested changes
slight comment changes

2022-11-21 16:55 UTC, Ludosss commented on src/main/java/ca/utoronto/fitbook/adapter/persistence/localmemory/ExerciseLocalMemoryRepository.java
> +     * @param exerciseIds The post ids to be fetched
rewrite comment to be "exercise ids"

2022-11-21 16:55 UTC, Ludosss commented on src/main/java/ca/utoronto/fitbook/adapter/persistence/firebase/ExerciseFirebaseRepository.java
> +     * @param exerciseIds The post ids to be fetched
rewrite comment to be "exercise ids"

2022-11-21 16:58 UTC, jpablo2002 commented on src/main/java/ca/utoronto/fitbook/adapter/persistence/localmemory/ExerciseLocalMemoryRepository.java
> +     * @param exerciseIds The post ids to be fetched
Good point, resolved!

2022-11-21 16:58 UTC, jpablo2002 commented on src/main/java/ca/utoronto/fitbook/adapter/persistence/firebase/ExerciseFirebaseRepository.java
> +     * @param exerciseIds The post ids to be fetched
Good point, resolved!

2022-11-22 02:13 UTC, Ludosss approved these changes
very nice

2022-11-22 03:09 UTC, youssefsoli approved these changes
Simple and short, looks good r+

2022-11-22 03:11 UTC, modaserMoj approved these changes
Implemented some changes to the exercise repo that helps members

2022-11-22 03:15 UTC, merged